"""add is_new field to users

Revision ID: 912215e24801
Revises: bad8138b8a19
Create Date: 2025-01-26 22:54:26.738530

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '912215e24801'
down_revision = 'bad8138b8a19'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_new', sa.Boolean(), nullable=False, server_default='true'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('is_new')

    # ### end Alembic commands ###
